version: '3.8'

services:
  web:
    build:
      context: .
    container_name: queue-app
    ports:
      - "4000:4000"
    env_file:
      - .env   # โหลด DATABASE_URL / NHSO_API_BASE_URL จากไฟล์นี้
    environment:
      TZ: Asia/Bangkok
    # volumes:                 # ถ้าต้องการแมปไฟล์
    #   - ./data:/app/data
