services:
  web:
    build:
      context: .
    container_name: queue-app
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      TZ: Asia/Bangkok
    volumes:
      - ./data:/app/data   # <<<< ตรงนี้ทำให้ไฟล์ settings.json โผล่ใน VS Code
