version: '3.8'

services:
  web:
    build:
      context: .
      args:
        # ส่งค่า DATABASE_URL เข้าไปตอน build จากไฟล์ .env
        DATABASE_URL: ${DATABASE_URL}
    container_name: Queue-App
    ports:
      - "4000:4000"
    env_file:
      - .env   # โหลดตัวแปรจากไฟล์ .env
    environment:
      TZ: Asia/Bangkok
      DATABASE_URL: ${DATABASE_URL}   # ใช้ค่าจาก .env
    volumes:
      - ./data:/app/data
