version: '3.8'

services:
  web:
    build:
      context: .
      args:
        DATABASE_URL: mysql://fenyb:0959611859Vi.@10.10.54.128:3306/dataqueue
    container_name: Queue-App
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - TZ=Asia/Bangkok
      - DATABASE_URL=mysql://fenyb:0959611859Vi.@10.10.54.128:3306/dataqueue
    volumes:
      - ./data:/app/data
  


