version: '3.8'

services:
  web:
    build:
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}   # ให้ Prisma เห็นตอน build
    image: queue-app:latest
    container_name: queue-app
    ports:
      - "4000:4000"
    env_file:
      - .env                           # โหลด DATABASE_URL และตัวอื่น ๆ
    environment:
      TZ: Asia/Bangkok
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      PORT: "4000"
    volumes:
      - ./data:/app/data               # <-- bind mount โฟลเดอร์ dataqueue โผล่ในโปรเจกต์
    restart: unless-stopped
